services:
  msusers:
    image: msusers
    build:
      context: ./msusers
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    restart: always
    networks:
      - msusers-network
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/msusers?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
      RABBITMQ_SERVER: rabbitmq

  msnotify:
    image: msnotify
    build:
      context: ./notify
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    restart: always
    networks:
      - msusers-network
    environment:
      - SPRING_DATA_MONGODB_URI=mongodb://mongodb:27017/notify
      - RABBITMQ_SERVER=rabbitmq
      - SPRING_APPLICATION_NAME=msnotify
    depends_on:
      - mongodb

  mysql:
    image: mysql:8.0.40
    command: mysqld --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: msusers
      MYSQL_TCP_PORT: 3306
    ports:
      - "3306:3306"
    volumes:
      - mysql-data:/var/lib/mysql
    networks:
      - msusers-network

  mongodb:
    image: mongo:latest
    container_name: "mongodb"
    environment:
      MONGO_INITDB_DATABASE: notify
    ports:
      - "27017:27017"
    networks:
      - msusers-network

  rabbitmq:
    image: rabbitmq:4.0-management
    container_name: rabbitmq_management
    ports:
      - "15672:15672"
      - "5672:5672"
    volumes:
      - /docker_conf/rabbitmq/data/:/var/lib/rabbitmq/
    environment:
      - RABBITMQ_DEFAULT_USER = guest
      - RABBITMQ_DEFAULT_PASS = guest
    restart: no
    networks:
      - msusers-network

volumes:
  mysql-data:
    driver: local
  mongo_data:
    driver: local

networks:
  msusers-network:
    driver: bridge